config/routes.rb
Rails.application.routes.draw do
  root 'landing#index'
  resources :profiles
  resources :conversations
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  has_many :messages
  has_many :profile_conversations
  has_many :profiles, through: :profile_conversations

  scope :between, ->(profile1_id, profile2_id) do
    joins(:profiles).where(profiles: {id: profile1_id}) & joins(:profiles).where(profiles: {id: profile2_id})
end

app/models/image_uploaders.rb
class ImageUploader < Shrine
  include ImageProcessing::MiniMagick

  plugin :activerecord
  plugin :determine_mime_type
  plugin :logging, logger: Rails.logger
  plugin :remove_attachment
  plugin :store_dimensions
  plugin :validation_helpers
  plugin :versions, names: [:original, :thumb]

  Attacher.validate do
    validate_max_size 3.megabytes, message: 'is too large (max is 2 MB)'
    validate_mime_type_inclusion ['image/jpg', 'image/jpeg', 'image/png', 'image/gif']
  end

  def process(io, context)
    case context[:phase]
    when :store
      thumb = resize_to_limit!(io.download, 200, 200)
      { original: io, thumb: thumb }
    end
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :conversation
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/profile_conversation.rb
class ProfileConversation < ApplicationRecord
  belongs_to :profile
  belongs_to :conversation
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:user_id, :name, :home_location, :profile_image_data)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/landing/index.html.erb
<div class="landing">
  <div class="signin">
      <%= link_to "Sign In", new_user_session_path, class:'btn btn-secondary' %>
  </div>
  <div class="signup">
      <%= link_to "Sign Up", new_user_registration_path, class:'btn btn-secondary' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HazKit</title>
    <%= csrf_meta_tags %>

    <!-- GOOGLE FONTS -->
    <link href="https://fonts.googleapis.com/css?family=Cabin:400,500|Permanent+Marker" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="top_nav">
          <h1>HazKit</h1>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- shrine upload button goes here -->
  <div class="btn btn-secondary">Upload new profile photo</div>


  <div class="field">
    <%= form.label :what_is_your_name? %>
    <%= form.text_field :name, id: :profile_name %>
  </div>

  <div class="field">
    <%= form.label :where_do_you_live? %>
    <%= form.text_field :home_location, id: :profile_home_location %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1 class = 'text-center'>Editing Profile</h1>

<div class='profilepic'><%#= image_tag @profile.profile_image_data %></div>

<div class='text-center'>
<%= render 'form', profile: @profile %>
</div>
<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Name</th>
      <th>Home location</th>
      <th>Profile image data</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.user %></td>
        <td><%= profile.name %></td>
        <td><%= profile.home_location %></td>
        <td><%= profile.profile_image_data %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>
<div class='container text-center'>
  <h1 class='text-center'>
    <%= @profile.name%>
  </h1>

  <div class='profilepic'><%#= image_tag @profile.profile_image_data %></div>
  <br><br>
  <%= link_to 'Edit', edit_profile_path(@profile) %>
  <br><br>
  <p>
    <strong>Rating: </strong>10
    <%#= waiting on posts models implementation %>
  </p>
  <p>
    <strong>Posts written: </strong>1
    <%#= waiting on posts models implementation %>
  </p>
  <p>
    <strong>Home location:</strong>
    <%= @profile.home_location %>
  </p>

  <%= link_to 'View all profiles', profiles_path %>
<div>